name: FMN Nieuws
url: https://fmn.nl/actueel/nieuws
item_selector: article.overview__item             # elk nieuwsitem staat in een <article> met class "overview__item"
title_selector: h3.overview__title a               # titel staat in <h3 class="overview__title"><a>
link_selector: h3.overview__title a                # link zit in hetzelfde <a>-element als de titel
summary_selector: div.overview__intro p            # korte samenvatting in <div class="overview__intro"><p>
date_selector: time.overview__date                 # publicatiedatum in <time class="overview__date">
date_attr: datetime                                # datumwaarde uit het datetime-attribuut
date_format: "%Y-%m-%dT%H:%M:%S%z"                  # ISO 8601 met tijdzone-offset
