name: Werken voor Nederland – Vacatures (CVG.09, CWD.08/CWD.04)
url: https://www.werkenvoornederland.nl/vacatures?type=vacature&vakgebied=CVG.09&werkdenkniveau=CWD.08,CWD.04
item_selector: li.vacature-overzicht__item             # elk vacatureblok staat in een <li> met deze class
title_selector: h2.vacature-overzicht__title a         # titel staat in <h2 class="vacature-overzicht__title"><a>
link_selector: h2.vacature-overzicht__title a          # link zit in hetzelfde <a>-element als de titel
summary_selector: p.vacature-overzicht__intro          # korte omschrijving in <p class="vacature-overzicht__intro">
date_selector: time.vacature-overzicht__datum          # publicatiedatum in <time class="vacature-overzicht__datum">
date_attr: datetime                                    # datumwaarde uit het datetime-attribuut
date_format: "%Y-%m-%d"                                # formaat zoals in de HTML (bv. 2025-08-21)
