id: custom-feed
source_url: https://www.nen.nl/nieuws
render: true
scroll_to_bottom: true
wait_for_selector: body.aw_blog-index-index.page-layout-2columns-right > div.page-wrapper > main.page-main > div.columns > div.column.main > div.blog-posts > article.blog-posts-post.blog-post > header.blog-post-header > h2.blog-post-title > a.blog-post-title-link
wait_for_count: 5

selectors:
  title: body.aw_blog-index-index.page-layout-2columns-right > div.page-wrapper > main.page-main > div.columns > div.column.main > div.blog-posts > article.blog-posts-post.blog-post > header.blog-post-header > h2.blog-post-title > a.blog-post-title-link
  date: body.aw_blog-index-index.page-layout-2columns-right > div.page-wrapper > main.page-main > div.columns > div.column.main > div.blog-posts > article.blog-posts-post.blog-post > header.blog-post-header > ul.blog-post-info > li.blog-post-info-item
  summary: main.page-main > div.columns > div.column.main > div.blog-posts > article.blog-posts-post.blog-post > div.blog-post-content > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > p:nth-of-type(1)
  image: div.page-wrapper > main.page-main > div.columns > div.column.main > div.blog-posts > article.blog-posts-post.blog-post > div.blog-post-featured-image-wrapper > a.blog-post-featured-image-link > picture:nth-of-type(1) > img.blog-post-lazyload-image.blog-post-featured-image

output:
  feed_file: docs/sites-nen-nieuws.xml
  site_name: www.nen.nl
  site_url: https://www.nen.nl/nieuws

limits:
  max_items: 5
  dedupe_on: url
