id: sites-nen-nieuws
source_url: https://www.nen.nl/nieuws
render: false
api:
  url: https://www.nen.nl/api/news?page=1&pageSize=10
  method: GET
  headers:
    Accept: application/json
    User-Agent: Mozilla/5.0 (compatible; FeedBuilder/1.0)
  pagination:
    param: page
    start: 1
    max_pages: 3

mapping:
  items: data
  title: title
  url: url
  date: publishDate
  summary: summary

date:
  input_format: auto
  tz: Europe/Amsterdam

output:
  feed_file: docs/sites-nen-nieuws.xml
  site_name: NEN – Nieuws en ontwikkelingen
  site_url: https://www.nen.nl/nieuws

limits:
  max_items: 30
  dedupe_on: url
