id: sites-nen-nieuws
source_url: https://www.nen.nl/nieuws
render: true
scroll_to_bottom: true
scroll_delay_seconds: 2
wait_for_selector: article.news-item
wait_for_count: 5
screenshot_on_render: true

request:
  user_agent: Mozilla/5.0 (compatible; FeedBuilder/1.0)
  delay_seconds: 1.0
  max_retries: 3

selectors:
  item: article.news-item
  title: h2.news-item__title a
  url: h2.news-item__title a@href
  date: time@datetime
  summary: p.news-item__intro

date:
  input_format: auto
  tz: Europe/Amsterdam

output:
  feed_file: docs/sites-nen-nieuws.xml
  site_name: NEN – Nieuws en ontwikkelingen
  site_url: https://www.nen.nl/nieuws

limits:
  max_items: 20
  dedupe_on: url
