site:
  naam: nen-nieuws
  titel: NEN – Nieuws en ontwikkelingen
  type: html
  bron:
    url: "https://www.nen.nl/nieuws-overzicht"

  selectors:
    items: "div.news-item"
    titel: "h2.news-title"
    link: "a::attr(href)"
    teaser: "div.news-intro"
    publicatie_datum: "span.news-date"
    afbeelding: "img::attr(src)"

  mapping:
    titel: "titel"
    link: "link"
    beschrijving: "teaser"
    publicatie_datum: "publicatie_datum"
    afbeelding: "afbeelding"

  transformaties:
    publicatie_datum:
      - type: date_format
        van: "d MMMM yyyy"
        naar: "EEE, dd MMM yyyy 00:00:00 Z"

  opties:
    output: "docs/sites-nen-nieuws.xml"
    feed_id: "https://facilitairinfo.github.io/Newsfeeds/sites-nen-nieuws.xml"
    datumformaat: "EEE, dd MMM yyyy HH:mm:ss Z"
    encoding: "UTF-8"
    absolute_links: true
