title: Envalue Inzichten
link: https://www.envalue.com/nl/inzichten/
description: Laatste inzichten en artikelen van Envalue
language: nl
max_items: 12
sources:
  - url: https://www.envalue.com/nl/inzichten/
    item_selector:
      - "article"
      - ".archive-list article"
      - ".posts article"
    title_selector:
      - "h2 a"
      - "h3 a"
      - "a[rel='bookmark']"
    link_selector:
      - "h2 a"
      - "h3 a"
      - "a[rel='bookmark']"
    summary_selector:
      - ".excerpt"
      - ".intro"
      - "p"
    date_selector:
      - "time"
      - ".date"
      - ".post-meta time"
    date_attr: datetime
