name: Envalue
url: https://www.envalue.com/nl/inzichten/
selectors:
  item: div.blog-card
  title: h3
  link: a
  date: span.date
date_format: '%d %B %Y'
use_playwright: true
output: docs/sites-Envalue-nieuws.xml
limits:
  max_items: 5
