site:
  naam: nen-nieuws
  titel: NEN – Nieuws en ontwikkelingen
  type: html
  bron:
    url: "https://www.nen.nl/nieuws"

selectors:
  items: "article.blog-posts-post"
  titel: "h2.blog-post-title a.blog-post-title-link"
  link: "h2.blog-post-title a.blog-post-title-link::attr(href)"
  teaser: "div.blog-post-content p"
  publicatie_datum: "ul.blog-post-info li::text"
  afbeelding: "img.blog-post-image::attr(src)"

mapping:
  titel: "titel"
  link: "link"
  beschrijving: "teaser"
  publicatie_datum: "publicatie_datum"
  afbeelding: "afbeelding"

transformaties:
  publicatie_datum:
    - type: date_format
      van: "dd-MM-yyyy"
      naar: "EEE, dd MMM yyyy 00:00:00 Z"

output:
  feed_file: docs/sites-nen-nieuws.xml
  feed_id: "https://facilitairinfo.github.io/Newsfeeds/sites-nen-nieuws.xml"
  site_name: NEN – Nieuws en ontwikkelingen
  site_url: https://www.nen.nl/nieuws
  datumformaat: "EEE, dd MMM yyyy HH:mm:ss Z"
  encoding: "UTF-8"
  absolute_links: true

limits:
  max_items: 5

render: true
scroll_to_bottom: true
wait_for_selector: "article.blog-posts-post"
wait_for_count: 3
