name: "cfp-nieuws"
url: "https://cfp.nl/nieuws-en-cases/"
scraper:
  item_selector: "div.blog_article"
  title_selector: "h6.blog_article__content_holder__title"
  link_selector: "a.blog_article__content_holder@href"
  date_selector: ".blog_article__content_holder__meta_data__date"
  date_format: "%d-%m-%Y"
  description_selector: ".blog_article__content_holder__content p, h6.blog_article__content_holder__title"
  category_selector: ".blog_article__content_holder__meta_data__term"
feed:
  title: "Nieuws & Cases - CFP"
  link: "https://cfp.nl/nieuws-en-cases/"
  description: "Laatste nieuws en cases van CFP Green Buildings"
  language: "nl"
