site:
  naam: werkenvoornederland-vacatures
  titel: Werken voor Nederland – Vacatures
  type: json
  bron:
    url: "https://api.cso20.net/v1/JobAPI/GetJobs"
    params:
      Type: "vacature"
      Vakgebied: "CVG.09"
      WerkDenkniveau: "CWD.08,CWD.04"
      PageSize: 6                      # Max 6 resultaten per call
      PageNumber: 1
      Sortering: "PublicatieDatum_desc" # Nieuwste eerst
      PublicatieDatumVanaf: "{{ vandaag_minus_2_dagen }}"
  mapping:
    titel: "Titel"
    link: "Url"
    organisatie: "Organisatie"
    publicatie_datum: "PublicatieDatum"
    locatie: "Standplaats"
  opties:
    output: "docs/sites-werkenvoornederland-vacatures.xml"
    feed_id: "https://facilitairinfo.github.io/Newsfeeds/sites-werkenvoornederland-vacatures.xml"
    paginering:
      parameter: "PageNumber"
      start: 1
      max_paginas: 1
    datumformaat: "yyyy-MM-dd'T'HH:mm:ss"
    encoding: "UTF-8"
