title: Werken voor Nederland – Vacatures (Facilitair/dienstverlening, niveaus HBO/WO)
link: https://www.werkenvoornederland.nl/vacatures?type=vacature&vakgebied=CVG.09&werkdenkniveau=CWD.08,CWD.04
description: Gefilterde vacatures bij de Rijksoverheid
language: nl
max_items: 20
sources:
  - url: https://www.werkenvoornederland.nl/vacatures?type=vacature&vakgebied=CVG.09&werkdenkniveau=CWD.08,CWD.04
    item_selector:
      - "li.vacature-overzicht__item"
      - "li.search-result"
      - "article"
    title_selector:
      - "h2 a"
      - "h3 a"
      - ".vacature-overzicht__title a"
    link_selector:
      - "h2 a"
      - "h3 a"
      - ".vacature-overzicht__title a"
    summary_selector:
      - ".vacature-overzicht__intro"
      - ".teaser"
      - "p"
    date_selector:
      - "time"
      - ".vacature-overzicht__datum"
      - ".date"
    date_attr: datetime
