name: Update feeds & status

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # elke 6 uur draaien (pas aan naar wens)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Haal de repo op
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Belangrijk voor pull/rebase

      # 2. Zet Python op
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Installeer dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run scraper
      - name: Run scraper
        run: python scripts/scrape_all.py

      # 5. Commit & push alleen bij wijzigingen
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Haal laatste remote main binnen
          git fetch origin main

          # Rebase bovenop de nieuwste main
          git rebase origin/main

          # Check of er wijzigingen zijn
          if [[ -n "$(git status --porcelain docs/*.xml feedstatus.json 2>/dev/null)" ]]; then
              git add docs/*.xml feedstatus.json
              git commit -m "Update feeds & status [skip ci]"
              git push origin main
          else
              echo "Geen wijzigingen in output, commit wordt overgeslagen."
          fi
