name: Update feeds en feedstatus

on:
  schedule:
    - cron: "0 6 * * *"  # elke dag om 06:00 UTC
  workflow_dispatch:     # handmatig starten mogelijk

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests feedparser

      # --- Optioneel: eerst alle feeds scrapen/bouwen ---
      - name: Scrape all feeds
        run: python scripts/scrape_all.py

      # --- Genereer de feedstatus.json ---
      - name: Generate feedstatus.json
        run: python scripts/gen_feedstatus.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add feedstatus.json
          git commit -m "Auto-update feeds en feedstatus" || echo "No changes to commit"
          git push
